spring.application.name=demo
spring.datasource.url=jdbc:mysql://localhost:3306/auth_system
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate settings
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
jwt.secret=your_super_secret_key_that_matches_the_main_auth_service
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081

media.service.url=http://localhost:8080

# MinIO Configuration (Keys updated to match @Value in MinioConfig)
minio.endpoint=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
minio.region=us-east-1

# razorpay.webhook.secret=YOUR_WEBHOOK_SECRET

# AWS / MinIO Bucket Configuration
aws.s3.bucket=my-media-bucket