spring.application.name=demo
# ----------------------------
# Shard 1 Configuration
shard1.datasource.jdbc-url=jdbc:mysql://localhost:3306/codewithmanoj
shard1.datasource.username=root
shard1.datasource.password=admin
shard1.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Shard 2 Configuration (Assuming you have a second one)
shard2.datasource.jdbc-url=jdbc:mysql://localhost:3037/codewithmanoj
shard2.datasource.username=root
shard2.datasource.password=
shard2.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true