spring.application.name=demo

# -------- Shard 1 --------
app.datasource.shard1.url=jdbc:mysql://localhost:3036/codewithmanoj
app.datasource.shard1.username=root
app.datasource.shard1.password=admin

# -------- Shard 2 --------
app.datasource.shard2.url=jdbc:mysql://localhost:3037/codewithmanoj
app.datasource.shard2.username=root
app.datasource.shard2.password=admin

# Common Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true