package com.example.demo.dto.ecom.payment;

public record PaymentVerificationRequest(
    String razorpayOrderId,   // The `order_xxx` ID
    String razorpayPaymentId, // The `pay_xxx` ID generated upon payment
    String razorpaySignature  // The HMAC SHA256 signature generated by Razorpay
) {}